### ISSUE TITLE
H3C移动项目新需求

### ISSUE THREAD

**Issue by HP-Dengwei** [HydraFramework/Hydra#12]
目前我们在下载数据或者执行一个命令时，会出现“正在加载”或者“Loading”页面，在这个过程中，是没有办法执行任何操作的，从客户端也没有办法写代码去停止这个进程，因为是被限制了。所以想请问一下，框架是否把这个进程放开，或者从框架方面做个调整，允许这个操作呢？

有问题随时和我联系。邓伟

**Comment by samchangme** [comment]
具体的busy如果是自己定义的，自己添加操作就可以取消了，这个是UI设计的问题
系统自带的startBusy stopBusy只是作为不允许用户干预场景下使用的，
因为具体取消方式各个场景不相同，所以如果需要允许用户干预，建议相应模块独立处理这块逻辑

**Comment by HP-Dengwei** [comment]
Ok，我们自己先研究一下，然后再决定怎么操作，谢谢

Best Regards
David Deng

GD China
HP Enterprise Services Apps
Telephone +862120266284
Email  wei.deng@hp.com
Mailing Address: No. 2557, Building D Jin Ke Road, Zhang Jiang Hi-Tech Development Zone, Shanghai China
[cid:image007.png@01CBB317.3031F070]
This message (including any attachments) contains confidential information intended for a specific individual and purpose, and is protected by law. If you are not the intended recipient, you should delete this message and are hereby notified that any disclosure, copying, or distribution of this message, or the taking of any action based on it, is strictly prohibited.
