### ISSUE TITLE
[Android] 拍照API没有回调onsuccess事件

### ISSUE THREAD

**Issue by hp-liangzhang** [HydraFramework/Hydra#39]
请使用以下账号进行测试。
测试账号：330000800138
Login之后点击“新顾问直通车”，再点击"上传身份证正面"。

如果遇到lua错误，请修改ApplyBC/client/default/ua/captureImage.lua中的第54行为
fileName. = “aa.jpg” --config.fileName

这个文件的第64行camera.takePhoto调用拍照的api。拍好照后应该调用onsuccess这个回调的。

iOS没有这个问题。

**Comment by samchangme** [comment]
确认下这个问题是否已结束

**Comment by hp-liangzhang** [comment]
没有问题了，多谢！
