### ISSUE TITLE
[iOS/Android] 能否暴露一个api，直接调用拍照，不出现选择拍照和相册

### ISSUE THREAD

**Issue by hp-liangzhang** [HydraFramework/Hydra#40]
能否暴露一个api，直接调用拍照，不出现选择拍照和相册。
多谢！
![screenshot_2014-06-26-10-04-20](https://cloud.githubusercontent.com/assets/4554733/3395176/01d91abc-fcf8-11e3-9c06-af7066489855.png)

**Comment by hydraadmin** [comment]
camera = true,false,nil 对应 相机拍照，取相册，旧方式

**Comment by hp-liangzhang** [comment]
感谢song和xiaoxiang，已达成
